/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Model.Domain.Professor;
import Model.Domain.Disciplina;
import Utils.DateFormat;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Karlos
 */
public class CadastraProfessor extends javax.swing.JInternalFrame {

    private Professor objprof;
    public CadastraProfessor() {
        initComponents();
        this.objprof = new Professor();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_dataNascProf = new javax.swing.JLabel();
        text_nomeProf = new javax.swing.JLabel();
        text_rgProf = new javax.swing.JLabel();
        text_cpfProf = new javax.swing.JLabel();
        c_dataNascProf = new javax.swing.JTextField();
        c_cpfProf = new javax.swing.JTextField();
        c_nomeProf = new javax.swing.JTextField();
        c_rgProf = new javax.swing.JTextField();
        botao_confirmarProf = new javax.swing.JButton();
        botao_cancelarProf = new javax.swing.JButton();
        text_formacaoProf = new javax.swing.JLabel();
        c_titulacaoProf = new javax.swing.JTextField();
        text_titulacaoProf = new javax.swing.JLabel();
        c_formacaoProf = new javax.swing.JTextField();
        text_dataAdmissaoProf = new javax.swing.JLabel();
        c_dataAdmissaoProf = new javax.swing.JTextField();
        titulo_cadProf = new javax.swing.JLabel();

        setBackground(new java.awt.Color(135, 192, 221));
        setMinimumSize(new java.awt.Dimension(549, 412));
        setPreferredSize(new java.awt.Dimension(549, 412));

        text_dataNascProf.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_dataNascProf.setText("Nascimento:");

        text_nomeProf.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_nomeProf.setText("Nome:");

        text_rgProf.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_rgProf.setText("RG:");

        text_cpfProf.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_cpfProf.setText("CPF:");

        c_dataNascProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_dataNascProfActionPerformed(evt);
            }
        });

        c_cpfProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cpfProfActionPerformed(evt);
            }
        });

        c_nomeProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nomeProfActionPerformed(evt);
            }
        });

        c_rgProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_rgProfActionPerformed(evt);
            }
        });

        botao_confirmarProf.setBackground(new java.awt.Color(153, 255, 153));
        botao_confirmarProf.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botao_confirmarProf.setForeground(new java.awt.Color(0, 0, 0));
        botao_confirmarProf.setText("CONFIRMAR");
        botao_confirmarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_confirmarProfActionPerformed(evt);
            }
        });

        botao_cancelarProf.setBackground(new java.awt.Color(255, 102, 102));
        botao_cancelarProf.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botao_cancelarProf.setForeground(new java.awt.Color(0, 0, 0));
        botao_cancelarProf.setText("CANCELAR");
        botao_cancelarProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_cancelarProfMouseClicked(evt);
            }
        });

        text_formacaoProf.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_formacaoProf.setText("Formação:");

        c_titulacaoProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_titulacaoProfActionPerformed(evt);
            }
        });

        text_titulacaoProf.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_titulacaoProf.setText("Nível de Titulação:");

        c_formacaoProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_formacaoProfActionPerformed(evt);
            }
        });

        text_dataAdmissaoProf.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_dataAdmissaoProf.setText("Data de Admissão:");

        c_dataAdmissaoProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_dataAdmissaoProfActionPerformed(evt);
            }
        });

        titulo_cadProf.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo_cadProf.setForeground(new java.awt.Color(0, 102, 102));
        titulo_cadProf.setText(" Cadastro de Professor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(botao_cancelarProf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_confirmarProf))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_dataAdmissaoProf)
                                    .addComponent(text_titulacaoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c_titulacaoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c_dataAdmissaoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text_dataNascProf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_dataNascProf, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text_nomeProf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c_nomeProf, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text_cpfProf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_cpfProf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text_rgProf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c_rgProf, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text_formacaoProf)
                                .addGap(18, 18, 18)
                                .addComponent(c_formacaoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(titulo_cadProf))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titulo_cadProf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_nomeProf)
                    .addComponent(c_nomeProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_dataNascProf)
                    .addComponent(c_dataNascProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(c_rgProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_rgProf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_cpfProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_cpfProf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_formacaoProf)
                    .addComponent(c_formacaoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_titulacaoProf)
                    .addComponent(c_titulacaoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_dataAdmissaoProf)
                    .addComponent(c_dataAdmissaoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_cancelarProf)
                    .addComponent(botao_confirmarProf)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_nomeProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nomeProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nomeProfActionPerformed

    private void c_cpfProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cpfProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cpfProfActionPerformed

    private void c_dataNascProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_dataNascProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_dataNascProfActionPerformed

    private void c_rgProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_rgProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_rgProfActionPerformed

    private void botao_confirmarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_confirmarProfActionPerformed
        try {

            String nome = "";
            LocalDate dataNascimento = null;
            String rg = "";
            String cpf = "";
            String formacao = "";
            String nivelTitulacao = "";
            LocalDate dataAdmissao = null;
            boolean ativo = false;
            
            
        if (this.c_nomeProf.getText().length() < 2) {
            throw new Mensagens("Nome deve conter ao menos 2 caracteres.");
            
        } else {
            nome = this.c_nomeProf.getText();
        }
        if (this.c_dataNascProf.getText().length() != 10) {
            throw new Mensagens("Data deve conter 10 caracteres.");
            
        } else {
             dataNascimento = DateFormat.converterDataSQL(this.c_dataNascProf.getText());
            
        }

        if (this.c_rgProf.getText().length() != 7) {
            throw new Mensagens("RG deve conter 7 caracteres.");
            
        } else {
            rg = this.c_rgProf.getText();
            
        }
        if (this.c_cpfProf.getText().length() != 11) {
            throw new Mensagens("CPF deve conter 11 caracteres.");
            
        } else {
            cpf = this.c_cpfProf.getText();
        
        }    
            
        if (this.c_formacaoProf.getText().length() < 5) {
            throw new Mensagens("Formação deve conter ao menos 5 caracteres");
            
        } else {
            formacao = this.c_formacaoProf.getText();
        }    
        
        if (this.c_titulacaoProf.getText().length() < 5) {
           throw new Mensagens("Titulação deve conter ao menos 5 caracteres");
           
        } else {
            nivelTitulacao = this.c_titulacaoProf.getText();
            
        }
        
        if (this.c_dataAdmissaoProf.getText().length() != 10) {
            throw new Mensagens("Data deve conter 10 caracteres.");
            
        } else {
             dataAdmissao = DateFormat.converterDataSQL(this.c_dataAdmissaoProf.getText());
        
        }
        
            try {
                if (this.objprof.InsertProfessorBD(dataAdmissao, formacao, nivelTitulacao, nome, dataNascimento, rg, cpf)) {
                    JOptionPane.showMessageDialog(rootPane, "Professor Cadastrado com Sucesso!");
                    
                    this.c_nomeProf.setText("");
                    this.c_dataNascProf.setText("");
                    this.c_rgProf.setText("");
                    this.c_cpfProf.setText("");
                    this.c_titulacaoProf.setText("");
                    this.c_dataAdmissaoProf.setText("");
                }   } catch (SQLException ex) {
                Logger.getLogger(CadastraProfessor.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
    } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
    } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um número.");
    }          
        
    
        
    }//GEN-LAST:event_botao_confirmarProfActionPerformed

    private void c_titulacaoProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_titulacaoProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_titulacaoProfActionPerformed

    private void c_formacaoProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_formacaoProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_formacaoProfActionPerformed

    private void c_dataAdmissaoProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_dataAdmissaoProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_dataAdmissaoProfActionPerformed

    private void botao_cancelarProfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_cancelarProfMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_cancelarProfMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cancelarProf;
    private javax.swing.JButton botao_confirmarProf;
    private javax.swing.JTextField c_cpfProf;
    private javax.swing.JTextField c_dataAdmissaoProf;
    private javax.swing.JTextField c_dataNascProf;
    private javax.swing.JTextField c_formacaoProf;
    private javax.swing.JTextField c_nomeProf;
    private javax.swing.JTextField c_rgProf;
    private javax.swing.JTextField c_titulacaoProf;
    private javax.swing.JLabel text_cpfProf;
    private javax.swing.JLabel text_dataAdmissaoProf;
    private javax.swing.JLabel text_dataNascProf;
    private javax.swing.JLabel text_formacaoProf;
    private javax.swing.JLabel text_nomeProf;
    private javax.swing.JLabel text_rgProf;
    private javax.swing.JLabel text_titulacaoProf;
    private javax.swing.JLabel titulo_cadProf;
    // End of variables declaration//GEN-END:variables
}
