/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Model.Domain.Aluno;
import Utils.DateFormat;
import java.awt.event.MouseEvent;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Karlos
 */
public class GerenciaAluno extends javax.swing.JInternalFrame {

    private Aluno objaluno;

    public GerenciaAluno() {
        initComponents();
        this.objaluno = new Aluno();
        this.carregaTabela();

        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo_cadAluno1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_aluno = new javax.swing.JTable();
        titulo_gerenAluno = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        text_nomeAluno = new javax.swing.JLabel();
        c_nomeAluno = new javax.swing.JTextField();
        text_dataNascAluno = new javax.swing.JLabel();
        c_dataNascAluno = new javax.swing.JTextField();
        text_rgAluno = new javax.swing.JLabel();
        c_rgAluno = new javax.swing.JTextField();
        text_cpfAluno = new javax.swing.JLabel();
        c_faseAluno = new javax.swing.JTextField();
        text_cursoAluno = new javax.swing.JLabel();
        botao_cancelarAluno = new javax.swing.JButton();
        botao_confirmarAluno = new javax.swing.JButton();
        selecao_cursoAluno = new javax.swing.JComboBox<>();
        titulo_cadAluno = new javax.swing.JLabel();
        text_faseAluno = new javax.swing.JLabel();
        c_cpfAluno1 = new javax.swing.JTextField();
        text_nomeAluno1 = new javax.swing.JLabel();
        c_nomeAluno1 = new javax.swing.JTextField();
        text_idadeAluno = new javax.swing.JLabel();
        c_dataNascAluno1 = new javax.swing.JTextField();
        text_rgProf = new javax.swing.JLabel();
        c_rgAluno1 = new javax.swing.JTextField();
        text_cpfAluno1 = new javax.swing.JLabel();
        c_cpfAluno2 = new javax.swing.JTextField();
        text_curso = new javax.swing.JLabel();
        c_curso = new javax.swing.JTextField();
        botao_apagarAluno = new javax.swing.JButton();
        botao_cancelarGerenAluno = new javax.swing.JButton();
        botao_alterarAluno = new javax.swing.JButton();
        text_faseAluno2 = new javax.swing.JLabel();
        c_faseAluno2 = new javax.swing.JTextField();

        titulo_cadAluno1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo_cadAluno1.setForeground(new java.awt.Color(0, 102, 102));
        titulo_cadAluno1.setText(" Cadastro de Alunos");

        setBackground(new java.awt.Color(135, 192, 221));
        setMinimumSize(new java.awt.Dimension(549, 412));
        setPreferredSize(new java.awt.Dimension(549, 412));

        tabela_aluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Matrícula", "Nome", "Nascimento", "RG", "CPF", "Curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_aluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_alunoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_aluno);
        if (tabela_aluno.getColumnModel().getColumnCount() > 0) {
            tabela_aluno.getColumnModel().getColumn(5).setResizable(false);
        }

        titulo_gerenAluno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo_gerenAluno.setForeground(new java.awt.Color(0, 102, 102));
        titulo_gerenAluno.setText("Gerenciamento de Alunos");

        jInternalFrame1.setBackground(new java.awt.Color(135, 192, 221));
        jInternalFrame1.setMinimumSize(new java.awt.Dimension(549, 412));
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(549, 412));

        text_nomeAluno.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_nomeAluno.setText("Nome:");

        c_nomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nomeAlunoActionPerformed(evt);
            }
        });

        text_dataNascAluno.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_dataNascAluno.setText("Data de nascimento:");

        c_dataNascAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_dataNascAlunoActionPerformed(evt);
            }
        });

        text_rgAluno.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_rgAluno.setText("RG:");

        c_rgAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_rgAlunoActionPerformed(evt);
            }
        });

        text_cpfAluno.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_cpfAluno.setText("CPF:");

        c_faseAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_faseAlunoActionPerformed(evt);
            }
        });

        text_cursoAluno.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_cursoAluno.setText("Curso:");

        botao_cancelarAluno.setBackground(new java.awt.Color(255, 102, 102));
        botao_cancelarAluno.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botao_cancelarAluno.setForeground(new java.awt.Color(0, 0, 0));
        botao_cancelarAluno.setText("CANCELAR");
        botao_cancelarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cancelarAlunoActionPerformed(evt);
            }
        });

        botao_confirmarAluno.setBackground(new java.awt.Color(153, 255, 153));
        botao_confirmarAluno.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botao_confirmarAluno.setForeground(new java.awt.Color(0, 0, 0));
        botao_confirmarAluno.setText("CONFIRMAR");
        botao_confirmarAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_confirmarAlunoMouseClicked(evt);
            }
        });
        botao_confirmarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_confirmarAlunoActionPerformed(evt);
            }
        });

        selecao_cursoAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selecao_cursoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecao_cursoAlunoActionPerformed(evt);
            }
        });

        titulo_cadAluno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo_cadAluno.setForeground(new java.awt.Color(0, 102, 102));
        titulo_cadAluno.setText(" Cadastro de Alunos");

        text_faseAluno.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_faseAluno.setText("Fase:");

        c_cpfAluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cpfAluno1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(botao_cancelarAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_confirmarAluno))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(text_cursoAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selecao_cursoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(text_cpfAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_cpfAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(text_rgAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c_rgAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(text_nomeAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c_nomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(text_dataNascAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_dataNascAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(text_faseAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c_faseAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(titulo_cadAluno))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titulo_cadAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_nomeAluno)
                    .addComponent(c_nomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_dataNascAluno)
                    .addComponent(c_dataNascAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_rgAluno)
                    .addComponent(c_rgAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_cpfAluno)
                    .addComponent(c_cpfAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_cursoAluno)
                    .addComponent(selecao_cursoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_faseAluno)
                    .addComponent(c_faseAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_cancelarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_confirmarAluno)))
        );

        text_nomeAluno1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_nomeAluno1.setText("Nome:");

        c_nomeAluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nomeAluno1ActionPerformed(evt);
            }
        });

        text_idadeAluno.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_idadeAluno.setText("Nascimento:");

        c_dataNascAluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_dataNascAluno1ActionPerformed(evt);
            }
        });

        text_rgProf.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_rgProf.setText("RG:");

        c_rgAluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_rgAluno1ActionPerformed(evt);
            }
        });

        text_cpfAluno1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_cpfAluno1.setText("CPF:");

        c_cpfAluno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cpfAluno2ActionPerformed(evt);
            }
        });

        text_curso.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_curso.setText("Curso:");

        c_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cursoActionPerformed(evt);
            }
        });

        botao_apagarAluno.setBackground(new java.awt.Color(255, 51, 51));
        botao_apagarAluno.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botao_apagarAluno.setForeground(new java.awt.Color(0, 0, 0));
        botao_apagarAluno.setText("APAGAR");
        botao_apagarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_apagarAlunoActionPerformed(evt);
            }
        });

        botao_cancelarGerenAluno.setBackground(new java.awt.Color(255, 102, 102));
        botao_cancelarGerenAluno.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botao_cancelarGerenAluno.setForeground(new java.awt.Color(0, 0, 0));
        botao_cancelarGerenAluno.setText("CANCELAR");
        botao_cancelarGerenAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cancelarGerenAlunoActionPerformed(evt);
            }
        });

        botao_alterarAluno.setBackground(new java.awt.Color(102, 102, 255));
        botao_alterarAluno.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botao_alterarAluno.setForeground(new java.awt.Color(0, 0, 0));
        botao_alterarAluno.setText("ALTERAR");
        botao_alterarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_alterarAlunoActionPerformed(evt);
            }
        });

        text_faseAluno2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_faseAluno2.setText("Fase:");

        c_faseAluno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_faseAluno2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_gerenAluno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text_idadeAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_dataNascAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text_curso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text_faseAluno2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_faseAluno2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text_nomeAluno1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_nomeAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text_cpfAluno1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_cpfAluno2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text_rgProf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_rgAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 224, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botao_cancelarGerenAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_alterarAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_apagarAluno))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_gerenAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_nomeAluno1)
                    .addComponent(c_nomeAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_idadeAluno)
                    .addComponent(c_dataNascAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_rgAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_rgProf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_cpfAluno1)
                    .addComponent(c_cpfAluno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_curso)
                    .addComponent(c_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_faseAluno2)
                    .addComponent(c_faseAluno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_apagarAluno)
                    .addComponent(botao_cancelarGerenAluno)
                    .addComponent(botao_alterarAluno)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 195, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 194, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabela_alunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_alunoMouseClicked
        if (this.tabela_aluno.getSelectedRow() != -1) {

            String nome = this.tabela_aluno.getValueAt(this.tabela_aluno.getSelectedRow(), 1).toString();
            String nascimento = DateFormat.converterDataString(this.tabela_aluno.getValueAt(this.tabela_aluno.getSelectedRow(), 2).toString());
            String rg = this.tabela_aluno.getValueAt(this.tabela_aluno.getSelectedRow(), 3).toString();
            String cpf = this.tabela_aluno.getValueAt(this.tabela_aluno.getSelectedRow(), 4).toString();
            String curso = this.tabela_aluno.getValueAt(this.tabela_aluno.getSelectedRow(), 5).toString();

            this.c_nomeAluno1.setText(nome);
            this.c_dataNascAluno1.setText(nascimento);
            this.c_rgAluno1.setText(rg);
            this.c_cpfAluno2.setText(cpf);
            this.c_curso.setText(curso);

        }

    }//GEN-LAST:event_tabela_alunoMouseClicked

    private void c_nomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nomeAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nomeAlunoActionPerformed

    private void c_dataNascAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_dataNascAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_dataNascAlunoActionPerformed

    private void c_rgAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_rgAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_rgAlunoActionPerformed

    private void c_faseAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_faseAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_faseAlunoActionPerformed

    private void botao_cancelarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cancelarAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_cancelarAlunoActionPerformed

    private void botao_confirmarAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_confirmarAlunoMouseClicked

    }//GEN-LAST:event_botao_confirmarAlunoMouseClicked

    private void botao_confirmarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_confirmarAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_confirmarAlunoActionPerformed

    private void selecao_cursoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecao_cursoAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecao_cursoAlunoActionPerformed

    private void c_cpfAluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cpfAluno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cpfAluno1ActionPerformed

    private void c_nomeAluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nomeAluno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nomeAluno1ActionPerformed

    private void c_dataNascAluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_dataNascAluno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_dataNascAluno1ActionPerformed

    private void c_rgAluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_rgAluno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_rgAluno1ActionPerformed

    private void c_cpfAluno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cpfAluno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cpfAluno2ActionPerformed

    private void c_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cursoActionPerformed

    private void botao_cancelarGerenAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cancelarGerenAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_cancelarGerenAlunoActionPerformed

    private void botao_alterarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_alterarAlunoActionPerformed
        try {
            int matricula = 0;
            String nome = "";
            LocalDate nascimento = null;
            String rg = "";
            String cpf = "";
            int fase = 0;
            String curso = "";

            if (this.c_nomeAluno1.getText().length() < 2) {
                throw new Mensagens("Nome deve conter ao menos 2 caracteres");
            } else {
                nome = this.c_nomeAluno1.getText();
            }

            if (this.c_dataNascAluno1.getText().length() != 10) {
                throw new Mensagens("Data deve conter 10 caracteres");
            } else {
                nascimento = DateFormat.converterDataSQL(this.c_dataNascAluno1.getText());
            }

            rg = this.c_rgAluno1.getText();
            cpf = this.c_cpfAluno2.getText();
            

            if (Integer.parseInt(this.c_faseAluno2.getText()) <= 0) {
                throw new Mensagens("Fase deve ser número e maior que zero");
            } else {
                fase = Integer.parseInt(this.c_faseAluno2.getText());
            }

            if (this.c_curso.getText().length() < 2) {
                throw new Mensagens("Curso deve conter mais de 2 caracteres");
            } else {
                curso = this.c_curso.getText();
            }

            if (this.tabela_aluno.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro selecione um aluno para alterar");
            } else {
                matricula = Integer.parseInt(this.tabela_aluno.getValueAt(this.tabela_aluno.getSelectedRow(), 0).toString());
            }

            //envia os dados para o controlador processar
            if (this.objaluno.UpdateAlunoBD(fase, curso, matricula, nome, nascimento, rg, cpf)) {
                //limpa os campos
                this.c_nomeAluno1.setText("");
                this.c_dataNascAluno1.setText("");
                this.c_rgAluno1.setText("");
                this.c_cpfAluno2.setText("");
                this.c_faseAluno2.setText("");
                this.c_curso.setText("");
                JOptionPane.showMessageDialog(rootPane, "Aluno alterado com Sucesso");
            }
            System.out.println(this.objaluno.getAlunos().toString());
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um número");
        } finally {
            carregaTabela();
        }


    }//GEN-LAST:event_botao_alterarAlunoActionPerformed

    private void botao_apagarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_apagarAlunoActionPerformed
        try {
            //validando dados da interface gráfica
            int matricula = 0;
            if (this.tabela_aluno.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione um Aluno para APAGAR");
            } else {
                matricula = Integer.parseInt(this.tabela_aluno.getValueAt(this.tabela_aluno.getSelectedRow(), 0).toString());
            }

            int resposta_usuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja APAGAR este aluno?");

            if (resposta_usuario == 0) {
                if (this.objaluno.DeletetAlunoBD(matricula)) {
                    this.c_nomeAluno1.setText("");
                    this.c_dataNascAluno1.setText("");
                    this.c_rgAluno1.setText("");
                    this.c_cpfAluno2.setText("");
                    this.c_faseAluno2.setText("");
                    this.c_curso.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Aluno apagado com sucesso");
                }
            }
            System.out.println(this.objaluno.getAlunos().toString());
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            this.carregaTabela();
        }

    }//GEN-LAST:event_botao_apagarAlunoActionPerformed

    private void c_faseAluno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_faseAluno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_faseAluno2ActionPerformed
    @SuppressWarnings("unchecked")
    public void carregaTabela() {

        DefaultTableModel modelo = (DefaultTableModel) this.tabela_aluno.getModel();
        modelo.setNumRows(0);

        List<Aluno> minhalista = new ArrayList<>();
        minhalista = objaluno.getAlunos();

        for (Aluno a : minhalista) {
            modelo.addRow(new Object[]{
                a.getMatricula(),
                a.getNome(),
                a.getDataNascimento(),
                a.getRg(),
                a.getCpf(),
                a.getCurso()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_alterarAluno;
    private javax.swing.JButton botao_apagarAluno;
    private javax.swing.JButton botao_cancelarAluno;
    private javax.swing.JButton botao_cancelarGerenAluno;
    private javax.swing.JButton botao_confirmarAluno;
    private javax.swing.JTextField c_cpfAluno1;
    private javax.swing.JTextField c_cpfAluno2;
    private javax.swing.JTextField c_curso;
    private javax.swing.JTextField c_dataNascAluno;
    private javax.swing.JTextField c_dataNascAluno1;
    private javax.swing.JTextField c_faseAluno;
    private javax.swing.JTextField c_faseAluno2;
    private javax.swing.JTextField c_nomeAluno;
    private javax.swing.JTextField c_nomeAluno1;
    private javax.swing.JTextField c_rgAluno;
    private javax.swing.JTextField c_rgAluno1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selecao_cursoAluno;
    private javax.swing.JTable tabela_aluno;
    private javax.swing.JLabel text_cpfAluno;
    private javax.swing.JLabel text_cpfAluno1;
    private javax.swing.JLabel text_curso;
    private javax.swing.JLabel text_cursoAluno;
    private javax.swing.JLabel text_dataNascAluno;
    private javax.swing.JLabel text_faseAluno;
    private javax.swing.JLabel text_faseAluno2;
    private javax.swing.JLabel text_idadeAluno;
    private javax.swing.JLabel text_nomeAluno;
    private javax.swing.JLabel text_nomeAluno1;
    private javax.swing.JLabel text_rgAluno;
    private javax.swing.JLabel text_rgProf;
    private javax.swing.JLabel titulo_cadAluno;
    private javax.swing.JLabel titulo_cadAluno1;
    private javax.swing.JLabel titulo_gerenAluno;
    // End of variables declaration//GEN-END:variables
}
