/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.event.WindowEvent;
import javax.swing.JPanel;

/**
 *
 * @author ricas
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    
    
    
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo = new javax.swing.JPanel();
        canto = new javax.swing.JPanel();
        botao_cadProf = new javax.swing.JPanel();
        indica_cadProf = new javax.swing.JPanel();
        text_cadProf = new javax.swing.JLabel();
        icon_cadProf = new javax.swing.JLabel();
        botao_gerenProf = new javax.swing.JPanel();
        indica_gerenProf = new javax.swing.JPanel();
        text_gerenProf = new javax.swing.JLabel();
        icon_gerenProf = new javax.swing.JLabel();
        botao_gerenAluno = new javax.swing.JPanel();
        indica_gerenAluno = new javax.swing.JPanel();
        text_gerenAluno = new javax.swing.JLabel();
        icon_gerenAluno = new javax.swing.JLabel();
        botao_cadAluno = new javax.swing.JPanel();
        indica_cadAluno = new javax.swing.JPanel();
        text_cadAluno = new javax.swing.JLabel();
        icon_cadAluno = new javax.swing.JLabel();
        botao_sobre = new javax.swing.JPanel();
        indica_sobre = new javax.swing.JPanel();
        text_sobre = new javax.swing.JLabel();
        icon_sobre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        text_Title = new javax.swing.JLabel();
        text_version = new javax.swing.JLabel();
        coruja = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botao_x = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPanel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ATHENA"); // NOI18N
        setBackground(new java.awt.Color(51, 102, 255));
        setUndecorated(true);
        setResizable(false);

        fundo.setBackground(new java.awt.Color(135, 192, 221));

        canto.setBackground(new java.awt.Color(0, 153, 255));
        canto.setForeground(new java.awt.Color(51, 51, 51));
        canto.setToolTipText("");
        canto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cantoMouseClicked(evt);
            }
        });

        botao_cadProf.setBackground(new java.awt.Color(0, 153, 255));
        botao_cadProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_cadProfMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botao_cadProfMousePressed(evt);
            }
        });
        botao_cadProf.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indica_cadProf.setOpaque(false);

        javax.swing.GroupLayout indica_cadProfLayout = new javax.swing.GroupLayout(indica_cadProf);
        indica_cadProf.setLayout(indica_cadProfLayout);
        indica_cadProfLayout.setHorizontalGroup(
            indica_cadProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        indica_cadProfLayout.setVerticalGroup(
            indica_cadProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        botao_cadProf.add(indica_cadProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        text_cadProf.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        text_cadProf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_cadProf.setText("Cadastrar Professor");
        botao_cadProf.add(text_cadProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 15, -1, 20));

        icon_cadProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/8541740_chalkboard_teacher_icon.png"))); // NOI18N
        botao_cadProf.add(icon_cadProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, 30));

        botao_gerenProf.setBackground(new java.awt.Color(0, 153, 255));
        botao_gerenProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_gerenProfMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botao_gerenProfMousePressed(evt);
            }
        });
        botao_gerenProf.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indica_gerenProf.setOpaque(false);

        javax.swing.GroupLayout indica_gerenProfLayout = new javax.swing.GroupLayout(indica_gerenProf);
        indica_gerenProf.setLayout(indica_gerenProfLayout);
        indica_gerenProfLayout.setHorizontalGroup(
            indica_gerenProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        indica_gerenProfLayout.setVerticalGroup(
            indica_gerenProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        botao_gerenProf.add(indica_gerenProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        text_gerenProf.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        text_gerenProf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_gerenProf.setText("Gerenciar Professor");
        botao_gerenProf.add(text_gerenProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        icon_gerenProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/8541623_book_reader_icon.png"))); // NOI18N
        botao_gerenProf.add(icon_gerenProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        botao_gerenAluno.setBackground(new java.awt.Color(0, 153, 255));
        botao_gerenAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_gerenAlunoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botao_gerenAlunoMousePressed(evt);
            }
        });
        botao_gerenAluno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indica_gerenAluno.setOpaque(false);

        javax.swing.GroupLayout indica_gerenAlunoLayout = new javax.swing.GroupLayout(indica_gerenAluno);
        indica_gerenAluno.setLayout(indica_gerenAlunoLayout);
        indica_gerenAlunoLayout.setHorizontalGroup(
            indica_gerenAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        indica_gerenAlunoLayout.setVerticalGroup(
            indica_gerenAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        botao_gerenAluno.add(indica_gerenAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        text_gerenAluno.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        text_gerenAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_gerenAluno.setText("Gerenciar Aluno");
        botao_gerenAluno.add(text_gerenAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        icon_gerenAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/6590551_and_books_education_learning_library_icon.png"))); // NOI18N
        botao_gerenAluno.add(icon_gerenAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        botao_cadAluno.setBackground(new java.awt.Color(0, 153, 255));
        botao_cadAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_cadAlunoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botao_cadAlunoMousePressed(evt);
            }
        });
        botao_cadAluno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indica_cadAluno.setOpaque(false);

        javax.swing.GroupLayout indica_cadAlunoLayout = new javax.swing.GroupLayout(indica_cadAluno);
        indica_cadAluno.setLayout(indica_cadAlunoLayout);
        indica_cadAlunoLayout.setHorizontalGroup(
            indica_cadAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        indica_cadAlunoLayout.setVerticalGroup(
            indica_cadAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        botao_cadAluno.add(indica_cadAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        text_cadAluno.setBackground(new java.awt.Color(0, 0, 0));
        text_cadAluno.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        text_cadAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_cadAluno.setText("Cadastrar Aluno");
        text_cadAluno.setToolTipText("");
        botao_cadAluno.add(text_cadAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 15, -1, 20));

        icon_cadAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cadAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/309036_student_education_study_icon.png"))); // NOI18N
        icon_cadAluno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botao_cadAluno.add(icon_cadAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, 30));

        botao_sobre.setBackground(new java.awt.Color(0, 153, 255));
        botao_sobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_sobreMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botao_sobreMousePressed(evt);
            }
        });
        botao_sobre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indica_sobre.setOpaque(false);

        javax.swing.GroupLayout indica_sobreLayout = new javax.swing.GroupLayout(indica_sobre);
        indica_sobre.setLayout(indica_sobreLayout);
        indica_sobreLayout.setHorizontalGroup(
            indica_sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        indica_sobreLayout.setVerticalGroup(
            indica_sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        botao_sobre.add(indica_sobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        text_sobre.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        text_sobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_sobre.setText("Sobre");
        botao_sobre.add(text_sobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        icon_sobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3162614_info_information_about_help_support_icon.png"))); // NOI18N
        botao_sobre.add(icon_sobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 255));

        text_Title.setBackground(new java.awt.Color(255, 255, 255));
        text_Title.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        text_Title.setText("ATHENA");

        text_version.setText("V1.0a");

        coruja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/6602523_halloween_owl_icon.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Seu gerenciador inteligente");

        javax.swing.GroupLayout cantoLayout = new javax.swing.GroupLayout(canto);
        canto.setLayout(cantoLayout);
        cantoLayout.setHorizontalGroup(
            cantoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botao_cadProf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botao_gerenAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botao_gerenProf, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
            .addComponent(botao_cadAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botao_sobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cantoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(cantoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cantoLayout.createSequentialGroup()
                        .addComponent(coruja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_version, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cantoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(cantoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cantoLayout.setVerticalGroup(
            cantoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cantoLayout.createSequentialGroup()
                .addGroup(cantoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cantoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(coruja))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cantoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(cantoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_Title)
                            .addComponent(text_version))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botao_cadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_cadProf, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_gerenAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(botao_gerenProf, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_sobre, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botao_x.setBackground(new java.awt.Color(102, 102, 255));
        botao_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botao_xMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout botao_xLayout = new javax.swing.GroupLayout(botao_x);
        botao_x.setLayout(botao_xLayout);
        botao_xLayout.setHorizontalGroup(
            botao_xLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );
        botao_xLayout.setVerticalGroup(
            botao_xLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jDesktopPanel.setBackground(new java.awt.Color(135, 192, 221));
        jDesktopPanel.setPreferredSize(new java.awt.Dimension(0, 412));

        javax.swing.GroupLayout jDesktopPanelLayout = new javax.swing.GroupLayout(jDesktopPanel);
        jDesktopPanel.setLayout(jDesktopPanelLayout);
        jDesktopPanelLayout.setHorizontalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPanelLayout.setVerticalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fundoLayout = new javax.swing.GroupLayout(fundo);
        fundo.setLayout(fundoLayout);
        fundoLayout.setHorizontalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addComponent(canto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoLayout.createSequentialGroup()
                        .addGap(0, 528, Short.MAX_VALUE)
                        .addComponent(botao_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fundoLayout.createSequentialGroup()
                        .addComponent(jDesktopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        fundoLayout.setVerticalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fundoLayout.createSequentialGroup()
                .addComponent(botao_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botao_cadAlunoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_cadAlunoMousePressed
        setColor(botao_cadAluno);
         resetColor(botao_cadProf);
          resetColor(botao_gerenAluno);
           resetColor(botao_gerenProf);
            resetColor(botao_sobre);
            
        indica_cadAluno.setOpaque(true);
         indica_cadProf.setOpaque(false);
          indica_gerenAluno.setOpaque(false);
           indica_gerenProf.setOpaque(false);
            indica_sobre.setOpaque(false);
            
                                       
           
    }//GEN-LAST:event_botao_cadAlunoMousePressed

    private void botao_cadProfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_cadProfMousePressed
        setColor(botao_cadProf);
         resetColor(botao_cadAluno);
          resetColor(botao_gerenAluno);
           resetColor(botao_gerenProf);
            resetColor(botao_sobre);
            
        indica_cadAluno.setOpaque(false);
         indica_cadProf.setOpaque(true);
          indica_gerenAluno.setOpaque(false);
           indica_gerenProf.setOpaque(false);
            indica_sobre.setOpaque(false);
            
             
        
    }//GEN-LAST:event_botao_cadProfMousePressed

    private void botao_gerenAlunoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_gerenAlunoMousePressed
        setColor(botao_gerenAluno);
         resetColor(botao_cadAluno);
          resetColor(botao_cadProf);
           resetColor(botao_gerenProf);
            resetColor(botao_sobre);
            
        indica_cadAluno.setOpaque(false);
         indica_cadProf.setOpaque(false);
          indica_gerenAluno.setOpaque(true);
           indica_gerenProf.setOpaque(false);
            indica_sobre.setOpaque(false);   
            
        
            
    }//GEN-LAST:event_botao_gerenAlunoMousePressed

    private void botao_gerenProfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_gerenProfMousePressed
        setColor(botao_gerenProf);
         resetColor(botao_cadAluno);
          resetColor(botao_cadProf);
           resetColor(botao_gerenAluno);
            resetColor(botao_sobre);
            
        indica_cadAluno.setOpaque(false);
         indica_cadProf.setOpaque(false);
          indica_gerenAluno.setOpaque(false);
           indica_gerenProf.setOpaque(true);
            indica_sobre.setOpaque(false);
            
        
            
    }//GEN-LAST:event_botao_gerenProfMousePressed

    private void botao_sobreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_sobreMousePressed
        setColor(botao_sobre);
         resetColor(botao_cadAluno);
          resetColor(botao_cadProf);
           resetColor(botao_gerenAluno);
            resetColor(botao_gerenProf);
            
        indica_cadAluno.setOpaque(false);
         indica_cadProf.setOpaque(false);
          indica_gerenAluno.setOpaque(false);
           indica_gerenProf.setOpaque(false);
            indica_sobre.setOpaque(true);
            
        
            
    }//GEN-LAST:event_botao_sobreMousePressed

    private void botao_xMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_xMousePressed
        System.exit(0);
    }//GEN-LAST:event_botao_xMousePressed

    private void botao_cadAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_cadAlunoMouseClicked
        CadastraAluno obj = new CadastraAluno();
        jDesktopPanel.add(obj).setVisible(true);
    }//GEN-LAST:event_botao_cadAlunoMouseClicked

    private void botao_cadProfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_cadProfMouseClicked
        CadastraProfessor obj = new CadastraProfessor();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(obj).setVisible(true);
    }//GEN-LAST:event_botao_cadProfMouseClicked

    private void botao_gerenAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_gerenAlunoMouseClicked
        GerenciaAluno obj = new GerenciaAluno();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(obj).setVisible(true);
    }//GEN-LAST:event_botao_gerenAlunoMouseClicked

    private void botao_gerenProfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_gerenProfMouseClicked
        GerenciaProfessor obj = new GerenciaProfessor();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(obj).setVisible(true);
    }//GEN-LAST:event_botao_gerenProfMouseClicked

    private void botao_sobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_sobreMouseClicked
        Sobre objj = new Sobre();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(objj).setVisible(true);
    }//GEN-LAST:event_botao_sobreMouseClicked

    private void cantoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cantoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cantoMouseClicked

    void setColor(JPanel panel){
        panel.setBackground(new Color(114,219,255));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(0,153,255));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botao_cadAluno;
    private javax.swing.JPanel botao_cadProf;
    private javax.swing.JPanel botao_gerenAluno;
    private javax.swing.JPanel botao_gerenProf;
    private javax.swing.JPanel botao_sobre;
    private javax.swing.JPanel botao_x;
    private javax.swing.JPanel canto;
    private javax.swing.JLabel coruja;
    private javax.swing.JPanel fundo;
    private javax.swing.JLabel icon_cadAluno;
    private javax.swing.JLabel icon_cadProf;
    private javax.swing.JLabel icon_gerenAluno;
    private javax.swing.JLabel icon_gerenProf;
    private javax.swing.JLabel icon_sobre;
    private javax.swing.JPanel indica_cadAluno;
    private javax.swing.JPanel indica_cadProf;
    private javax.swing.JPanel indica_gerenAluno;
    private javax.swing.JPanel indica_gerenProf;
    private javax.swing.JPanel indica_sobre;
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel text_Title;
    private javax.swing.JLabel text_cadAluno;
    private javax.swing.JLabel text_cadProf;
    private javax.swing.JLabel text_gerenAluno;
    private javax.swing.JLabel text_gerenProf;
    private javax.swing.JLabel text_sobre;
    private javax.swing.JLabel text_version;
    // End of variables declaration//GEN-END:variables
}
